package com.comunidapp.app.domain.canonical

import com.comunidapp.app.domain.auth.LeoVerAuthDomains

/**
 * REBASE-03D — identity of the canonical Staging project.
 * Never point clients at the legacy project. Never embed service_role.
 *
 * [STAGING_URL] is the technical API host. Auth/OAuth branding uses
 * [com.comunidapp.app.domain.auth.LeoVerAuthDomains] when Custom Domain is active.
 */
object CanonicalBackend {
    const val STAGING_PROJECT_REF = "tobqbddfcyitwgbkthhy"
    const val STAGING_URL = "https://tobqbddfcyitwgbkthhy.supabase.co"
    const val LEGACY_PROJECT_REF = "wystsapjfpdtoprlmizz"

    const val LOCATION_NODES = "location_nodes"
    const val PERSONS = "persons"
    const val PETS = "pets"
    const val FRIENDSHIPS = "friendships"
    const val RPC_LIST_MY_FRIENDSHIPS = "canon_list_my_friendships"
    const val RPC_SEND_FRIEND_REQUEST = "canon_send_friend_request"
    const val RPC_RESPOND_FRIEND_REQUEST = "canon_respond_friend_request"
    const val RPC_CANCEL_FRIEND_REQUEST = "canon_cancel_friend_request"
    const val RPC_RECORD_STORY_VIEW = "canon_record_story_view"
    const val RPC_LIST_STORY_VIEWERS = "canon_list_story_viewers"
    const val RPC_REACT_STORY = "canon_react_story"
    const val RPC_COMMENT_STORY = "canon_comment_story"
    const val RPC_LIST_STORY_COMMENTS = "canon_list_story_comments"
    const val PET_RESPONSIBILITY_LINKS = "pet_responsibility_links"
    const val MEDIA_ASSETS = "media_assets"
    const val VITACORA_PROFILES = "vitacora_profiles"
    const val VITACORA_MOMENTS = "vitacora_moments"
    const val VITACORA_ACCESS_GRANTS = "vitacora_access_grants"
    const val VITACORA_UPDATE_PROPOSALS = "vitacora_update_proposals"

    const val RPC_CREATE_PET = "canon_create_pet"
    const val RPC_UPDATE_PET = "canon_update_pet"
    const val RPC_SET_PET_AVATAR = "canon_set_pet_avatar"
    const val RPC_SET_PERSON_AVATAR = "canon_set_person_avatar"
    const val RPC_LIST_PET_HOLDERS = "canon_list_pet_holders"
    const val RPC_IS_USERNAME_AVAILABLE = "canon_is_username_available"
    const val RPC_PUBLIC_ADOPTION = "canon_public_adoption"
    const val RPC_RECORD_PET_ALLERGY = "canon_record_pet_allergy"
    const val RPC_RECORD_PET_MEDICATION = "canon_record_pet_medication"
    const val RPC_RECORD_PET_VACCINATION = "canon_record_pet_vaccination"
    const val RPC_RECORD_PET_PARASITE_TREATMENT = "canon_record_pet_parasite_treatment"
    const val RPC_RECORD_PET_WEIGHT = "canon_record_pet_weight"
    const val RPC_RECORD_PET_CONDITION = "canon_record_pet_condition"
    const val RPC_SET_PET_CARE_INSTRUCTIONS = "canon_set_pet_care_instructions"
    const val RPC_ADD_PET_PERSON = "canon_add_pet_person"
    const val RPC_SET_ORG_RESPONSIBLE = "canon_set_org_responsible"
    const val RPC_OPEN_CUSTODY = "canon_open_custody"
    const val RPC_CLOSE_CUSTODY = "canon_close_custody"
    const val RPC_CREATE_MOMENT = "canon_create_moment"
    const val RPC_GRANT_VITACORA = "canon_grant_vitacora"
    const val RPC_REVOKE_VITACORA = "canon_revoke_vitacora"
    const val RPC_CREATE_PROPOSAL = "canon_create_proposal"
    const val RPC_DECIDE_PROPOSAL = "canon_decide_proposal"
    const val RPC_REGISTER_MEDIA = "canon_register_media"
    const val RPC_PUBLIC_PET = "canon_public_pet"
    const val RPC_PUBLIC_LOST_FOUND = "canon_public_lost_found"
    const val RPC_CREATE_ORGANIZATION = "canon_create_organization"
    const val RPC_CREATE_PROVIDER = "canon_create_provider"
    const val RPC_UPSERT_PROVIDER = "canon_upsert_provider"
    const val RPC_CREATE_BOOKING = "canon_create_booking"
    const val RPC_START_CONVERSATION = "canon_start_conversation"
    const val RPC_INVITE_GUARDIAN = "canon_invite_guardian"
    const val RPC_ACCEPT_GUARDIAN = "canon_accept_guardian"
    const val RPC_RECORD_CONSENT = "canon_record_consent"
    const val RPC_GET_PET_HEALTH = "canon_get_pet_health"
    const val RPC_END_PET_RESPONSIBILITY = "canon_end_pet_responsibility"
    const val RPC_LIST_LOCATION_CATALOG = "canon_list_location_catalog"
    const val RPC_UPDATE_MY_PERSON = "canon_update_my_person"
    const val RPC_PROVISION_MY_PERSON = "canon_provision_my_person"
    const val RPC_GET_PUBLIC_PERSON = "canon_get_public_person"
    const val RPC_LIST_VITACORA_MOMENTS = "canon_list_vitacora_moments"
    const val RPC_LIST_VITACORA_GRANTS = "canon_list_vitacora_grants"
    const val RPC_LIST_VITACORA_PROPOSALS = "canon_list_vitacora_proposals"
    const val RPC_CREATE_LOST_FOUND = "canon_create_lost_found"
    const val RPC_LIST_LOST_FOUND = "canon_list_lost_found"
    const val RPC_RESOLVE_LOST_FOUND = "canon_resolve_lost_found"
    const val RPC_CREATE_ADOPTION = "canon_create_adoption"
    const val RPC_LIST_ADOPTIONS = "canon_list_adoptions"
    const val RPC_CLOSE_ADOPTION = "canon_close_adoption"
    const val RPC_SET_ADOPTION_STATUS = "canon_set_adoption_status"
    const val RPC_APPLY_ADOPTION = "canon_apply_adoption"
    const val RPC_LIST_MY_ORGANIZATIONS = "canon_list_my_organizations"
    const val RPC_CREATE_SOCIAL_POST = "canon_create_social_post"
    const val RPC_LIST_SOCIAL_FEED = "canon_list_social_feed"
    const val RPC_REACT_SOCIAL_POST = "canon_react_social_post"
    const val RPC_COMMENT_SOCIAL_POST = "canon_comment_social_post"
    const val RPC_LIST_CONVERSATIONS = "canon_list_conversations"
    const val RPC_LIST_MESSAGES = "canon_list_messages"
    const val RPC_SEND_MESSAGE = "canon_send_message"
    const val RPC_LIST_PROVIDERS = "canon_list_providers"
    const val RPC_LIST_MY_BOOKINGS = "canon_list_my_bookings"
    const val RPC_LIST_EVENTS = "canon_list_events"
    const val RPC_CREATE_EVENT = "canon_create_event"
    const val RPC_LIST_DONATION_CAMPAIGNS = "canon_list_donation_campaigns"
    const val RPC_CREATE_DONATION_CAMPAIGN = "canon_create_donation_campaign"
    const val RPC_UPSERT_FOSTER_PROFILE = "canon_upsert_foster_profile"
    const val RPC_GET_MY_FOSTER_PROFILE = "canon_get_my_foster_profile"
    const val RPC_LIST_FOSTER_PLACEMENTS = "canon_list_foster_placements"
    const val RPC_CREATE_FOSTER_PLACEMENT = "canon_create_foster_placement"
    const val RPC_SET_PROVIDER_PUBLIC_GEO = "canon_set_provider_public_geo"
    const val RPC_SET_PROVIDER_WEEKLY_HOURS = "canon_set_provider_weekly_hours"
    const val RPC_LIST_PROVIDER_WEEKLY_HOURS = "canon_list_provider_weekly_hours"
    const val RPC_LIST_DAYCARE_RESERVATIONS = "canon_list_daycare_reservations"
    const val RPC_LIST_DAYCARE_GUESTS = "canon_list_daycare_guests"
    const val RPC_SET_PERSON_CAPABILITY = "canon_set_person_capability"
    const val RPC_LIST_MY_PERSON_CAPABILITIES = "canon_list_my_person_capabilities"
    const val RPC_SEARCH_PERSONS = "canon_search_persons"
    const val RPC_INVITE_ORG_MEMBER = "canon_invite_organization_member"
    const val RPC_LIST_ORG_INVITATIONS = "canon_list_org_invitations"
    const val RPC_LIST_MY_ORG_INVITATIONS = "canon_list_my_org_invitations"
    const val RPC_ACCEPT_ORG_INVITATION = "canon_accept_org_invitation"
    const val RPC_REJECT_ORG_INVITATION = "canon_reject_org_invitation"
    const val RPC_UPSERT_TUTORIAL_PROGRESS = "canon_upsert_tutorial_progress"
    const val RPC_LIST_TUTORIAL_PROGRESS = "canon_list_tutorial_progress"
    const val RPC_CREATE_STORY = "canon_create_story"
    const val RPC_LIST_ACTIVE_STORIES = "canon_list_active_stories"
    const val RPC_LIST_SOCIAL_COMMENTS = "canon_list_social_comments"
    const val RPC_DELETE_OWN_COMMENT = "canon_delete_own_comment"
    const val RPC_LIST_COUNTRY_MARKETS = "canon_list_country_markets"
    const val RPC_IMPORT_CREATE_JOB = "canon_import_create_job"
    const val RPC_IMPORT_ANALYZE = "canon_import_analyze"
    const val RPC_IMPORT_CONFIRM = "canon_import_confirm"
    const val RPC_IMPORT_GET = "canon_import_get"
    const val RPC_IMPORT_LIST = "canon_import_list"
    const val RPC_ADMIN_SEARCH_ORGS = "canon_admin_search_organizations"
    const val RPC_ADMIN_SET_ORG_VERIFICATION = "canon_admin_set_org_verification"
    const val RPC_ADMIN_SET_RESCUER_VERIFICATION = "canon_admin_set_rescuer_verification"
    const val RPC_ADMIN_SEARCH_RESCUERS = "canon_admin_search_rescuers"
    const val RPC_SEARCH_VITACORA_NUMBER = "canon_search_vitacora_number"
    const val RPC_LIST_SPECIES = "canon_list_species"
    const val RPC_LIST_BREEDS = "canon_list_breeds"
    const val RPC_LIST_PET_HEALTH_PRODUCTS = "canon_list_pet_health_products"
    const val RPC_ADMIN_LIST_SPECIES = "canon_admin_list_species"
    const val RPC_ADMIN_UPSERT_SPECIES = "canon_admin_upsert_species"
    const val RPC_ADMIN_LIST_BREEDS = "canon_admin_list_breeds"
    const val RPC_ADMIN_UPSERT_BREED = "canon_admin_upsert_breed"
    const val RPC_ADMIN_LIST_HEALTH_PRODUCTS = "canon_admin_list_pet_health_products"
    const val RPC_ADMIN_UPSERT_HEALTH_PRODUCT = "canon_admin_upsert_pet_health_product"
    const val RPC_ADMIN_LIST_LOCATION_CATALOG = "canon_admin_list_location_catalog"
    const val RPC_ADMIN_UPSERT_LOCATION_NODE = "canon_admin_upsert_location_node"

    fun isCanonicalStagingUrl(url: String?): Boolean {
        if (url.isNullOrBlank()) return false
        if (url.contains(STAGING_PROJECT_REF, ignoreCase = true)) return true
        return LeoVerAuthDomains.isOfficialStagingAuthHost(url)
    }

    fun isLegacyProjectUrl(url: String?): Boolean =
        !url.isNullOrBlank() && url.contains(LEGACY_PROJECT_REF, ignoreCase = true)
}
