#!/usr/bin/env bash
# Idempotent LeoVer Cloud bootstrap.
# Installs a Linux JDK 21 check, Android SDK command-line packages, and gradlew.
# Does not install an emulator, system images, Docker, or production secrets.
#
# Cursor Environment Install Script:
#   bash scripts/cloud/bootstrap-cloud.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

log() { printf '[bootstrap-cloud] %s\n' "$*"; }

require_jdk21() {
  local candidate=""
  if [[ -n "${JAVA_HOME:-}" && -x "${JAVA_HOME}/bin/java" ]]; then
    candidate="$JAVA_HOME"
  fi
  if [[ -z "$candidate" ]]; then
    local path
    for path in \
      /usr/lib/jvm/java-21-openjdk-amd64 \
      /usr/lib/jvm/java-21-openjdk-arm64 \
      /usr/lib/jvm/temurin-21-jdk-amd64 \
      /usr/lib/jvm/temurin-21-jdk-arm64
    do
      if [[ -x "$path/bin/java" ]]; then
        candidate="$path"
        break
      fi
    done
  fi
  if [[ -z "$candidate" ]]; then
    log "JDK 21 not found. Install OpenJDK 21 and re-run."
    exit 1
  fi
  local version
  version="$("$candidate/bin/java" -version 2>&1 | head -n 1 || true)"
  case "$version" in
    *'"21.'*|*'version "21'*|*'openjdk version "21'*) ;;
    *)
      log "JAVA_HOME must be JDK 21. Found: $version ($candidate)"
      exit 1
      ;;
  esac
  export JAVA_HOME="$candidate"
  export PATH="${JAVA_HOME}/bin:${PATH}"
  log "JDK 21: $JAVA_HOME"
}

ANDROID_HOME="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-${HOME}/Android/Sdk}}"
export ANDROID_HOME
export ANDROID_SDK_ROOT="$ANDROID_HOME"

CMDLINE_REV="13114758"
CMDLINE_ZIP="commandlinetools-linux-${CMDLINE_REV}_latest.zip"
CMDLINE_URL="https://dl.google.com/android/repository/${CMDLINE_ZIP}"
SDKMANAGER="${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager"

ensure_cmdline_tools() {
  if [[ -x "$SDKMANAGER" ]]; then
    log "Android cmdline-tools already present"
    return 0
  fi
  log "Installing Android cmdline-tools into ${ANDROID_HOME}"
  mkdir -p "${ANDROID_HOME}/cmdline-tools"
  local tmp
  tmp="$(mktemp -d)"
  curl -fsSL "$CMDLINE_URL" -o "${tmp}/${CMDLINE_ZIP}"
  unzip -q "${tmp}/${CMDLINE_ZIP}" -d "$tmp"
  rm -rf "${ANDROID_HOME}/cmdline-tools/latest"
  mkdir -p "${ANDROID_HOME}/cmdline-tools/latest"
  # The zip extracts a single "cmdline-tools" directory.
  cp -a "${tmp}/cmdline-tools/." "${ANDROID_HOME}/cmdline-tools/latest/"
  rm -rf "$tmp"
  chmod +x "$SDKMANAGER" || true
}

package_installed() {
  local pkg="$1"
  "$SDKMANAGER" --list_installed 2>/dev/null | awk '{print $1}' | grep -Fxq "$pkg"
}

install_package() {
  local pkg="$1"
  if package_installed "$pkg"; then
    log "Already installed: $pkg"
    return 0
  fi
  log "Installing $pkg"
  "$SDKMANAGER" --install "$pkg"
}

write_local_properties() {
  local props="${REPO_ROOT}/local.properties"
  local sdk_line="sdk.dir=${ANDROID_HOME}"
  if [[ -f "$props" ]] && grep -q '^sdk.dir=' "$props"; then
    if grep -qx "$sdk_line" "$props"; then
      log "local.properties sdk.dir already set"
      return 0
    fi
    local tmp
    tmp="$(mktemp)"
    grep -v '^sdk.dir=' "$props" > "$tmp" || true
    printf '%s\n' "$sdk_line" >> "$tmp"
    mv "$tmp" "$props"
  else
    printf '%s\n' "$sdk_line" >> "$props"
  fi
  log "Wrote sdk.dir to local.properties (gitignored)"
}

write_env_hint() {
  local hint="${HOME}/.leover-cloud-env.sh"
  cat > "$hint" <<EOF
# Generated by scripts/cloud/bootstrap-cloud.sh. Source from interactive shells.
export JAVA_HOME=${JAVA_HOME}
export ANDROID_HOME=${ANDROID_HOME}
export ANDROID_SDK_ROOT=${ANDROID_HOME}
export PATH="\${JAVA_HOME}/bin:\${ANDROID_HOME}/cmdline-tools/latest/bin:\${ANDROID_HOME}/platform-tools:\${PATH}"
EOF
  log "Env hint: $hint"
}

require_jdk21
ensure_cmdline_tools
export PATH="${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools:${PATH}"

log "Accepting Android SDK licenses"
yes | "$SDKMANAGER" --licenses >/dev/null || true

# App compileSdk is android-36.1. Shared compileSdk is 36.
# platform-tools is useful for adb-less builds; emulator and system images are intentionally absent.
install_package "platform-tools"
install_package "platforms;android-36"
install_package "platforms;android-36.1"
install_package "build-tools;36.1.0"

if [[ -f "${REPO_ROOT}/gradlew" ]]; then
  chmod +x "${REPO_ROOT}/gradlew"
  log "gradlew is executable"
else
  log "gradlew missing at ${REPO_ROOT}/gradlew"
  exit 1
fi

write_local_properties
write_env_hint

log "Bootstrap complete"
log "JAVA_HOME=${JAVA_HOME}"
log "ANDROID_HOME=${ANDROID_HOME}"
log "Emulator: not installed"
log "System images: not installed"
log "Next: bash scripts/qa/run-regression.sh"
